#include "pr_psx_gte_direct.h"

#include <cstddef>

namespace PrPsxGteDirect {
namespace {

constexpr uint32_t kFlagError = 1u << 31u;
constexpr std::array<uint32_t, 3> kFlagMac123Overflow{{
    1u << 30u, 1u << 29u, 1u << 28u,
}};
constexpr std::array<uint32_t, 3> kFlagMac123Underflow{{
    1u << 27u, 1u << 26u, 1u << 25u,
}};
constexpr std::array<uint32_t, 3> kFlagIr123Saturated{{
    1u << 24u, 1u << 23u, 1u << 22u,
}};
constexpr uint32_t kFlagSzSaturated = 1u << 18u;
constexpr uint32_t kFlagDivideOverflow = 1u << 17u;
constexpr uint32_t kFlagMac0Overflow = 1u << 16u;
constexpr uint32_t kFlagMac0Underflow = 1u << 15u;
constexpr uint32_t kFlagSxSaturated = 1u << 14u;
constexpr uint32_t kFlagSySaturated = 1u << 13u;
constexpr uint32_t kFlagIr0Saturated = 1u << 12u;
constexpr uint32_t kFlagErrorSourceMask = 0x7F87E000u;
constexpr int64_t kMac123Min = -(int64_t{1} << 43u);
constexpr int64_t kMac123Max = (int64_t{1} << 43u) - 1;
constexpr int64_t kMac0Min = -(int64_t{1} << 31u);
constexpr int64_t kMac0Max = (int64_t{1} << 31u) - 1;

int32_t SignExtendLow16(uint32_t value) {
    return static_cast<int16_t>(value & 0xFFFFu);
}

int32_t SignExtendHigh16(uint32_t value) {
    return static_cast<int16_t>(value >> 16);
}

uint32_t ClampUnsigned16(int64_t value) {
    if (value <= 0) {
        return 0;
    }
    if (value > 0xFFFF) {
        return 0xFFFFu;
    }
    return static_cast<uint32_t>(value);
}

int32_t TruncateSigned32(int64_t value) {
    const uint32_t bits = static_cast<uint32_t>(value);
    if ((bits & 0x80000000u) == 0u) {
        return static_cast<int32_t>(bits);
    }
    return static_cast<int32_t>(
        static_cast<int64_t>(bits) - 0x100000000ll);
}

int64_t ArithmeticShiftRight(int64_t value, uint32_t bits) {
    if (value >= 0) {
        return value >> bits;
    }
    const uint64_t magnitude =
        static_cast<uint64_t>(-(value + 1)) + 1u;
    const uint64_t rounded =
        (magnitude + ((uint64_t{1} << bits) - 1u)) >> bits;
    return -static_cast<int64_t>(rounded);
}

int64_t SignExtend44(int64_t value) {
    constexpr uint64_t mask = (uint64_t{1} << 44u) - 1u;
    constexpr uint64_t sign = uint64_t{1} << 43u;
    const uint64_t bits = static_cast<uint64_t>(value) & mask;
    if ((bits & sign) == 0u) {
        return static_cast<int64_t>(bits);
    }
    return static_cast<int64_t>(bits) - (int64_t{1} << 44u);
}

void CheckMac123Overflow(int64_t value,
                         std::size_t component,
                         uint32_t& flags) {
    if (value < kMac123Min) {
        flags |= kFlagMac123Underflow[component];
    } else if (value > kMac123Max) {
        flags |= kFlagMac123Overflow[component];
    }
}

int64_t CheckAndSignExtendMac44(int64_t value,
                                std::size_t component,
                                uint32_t& flags) {
    CheckMac123Overflow(value, component, flags);
    return SignExtend44(value);
}

void CheckMac0Overflow(int64_t value, uint32_t& flags) {
    if (value < kMac0Min) {
        flags |= kFlagMac0Underflow;
    } else if (value > kMac0Max) {
        flags |= kFlagMac0Overflow;
    }
}

int32_t ClampIr123(int32_t value,
                   std::size_t component,
                   uint32_t& flags) {
    if (value < -0x8000) {
        flags |= kFlagIr123Saturated[component];
        return -0x8000;
    }
    if (value > 0x7FFF) {
        flags |= kFlagIr123Saturated[component];
        return 0x7FFF;
    }
    return value;
}

uint16_t ClampIr0(int32_t value, uint32_t& flags) {
    if (value < 0) {
        flags |= kFlagIr0Saturated;
        return 0;
    }
    if (value > 0x1000) {
        flags |= kFlagIr0Saturated;
        return 0x1000u;
    }
    return static_cast<uint16_t>(value);
}

uint16_t ClampSz(int64_t value, uint32_t& flags) {
    if (value < 0) {
        flags |= kFlagSzSaturated;
        return 0;
    }
    if (value > 0xFFFF) {
        flags |= kFlagSzSaturated;
        return 0xFFFFu;
    }
    return static_cast<uint16_t>(value);
}

int32_t ClampScreenCoordinate(int64_t value,
                              uint32_t flag,
                              uint32_t& flags) {
    if (value < -0x400) {
        flags |= flag;
        return -0x400;
    }
    if (value > 0x3FF) {
        flags |= flag;
        return 0x3FF;
    }
    return static_cast<int32_t>(value);
}

uint32_t CountLeadingZeros16(uint16_t value) {
    if (value == 0u) {
        return 16u;
    }
    uint32_t count = 0u;
    for (uint16_t bit = 0x8000u; (value & bit) == 0u; bit >>= 1u) {
        ++count;
    }
    return count;
}

uint32_t UnrReciprocalTableEntry(uint32_t index) {
    // The 257-entry GTE reciprocal seed table is exactly generated by this
    // integer expression, avoiding an external emulator table dependency.
    const int32_t generated = static_cast<int32_t>(
        ((0x40000u / (index + 0x100u) + 1u) / 2u)) - 0x101;
    if (generated < 0) {
        return 0u;
    }
    if (generated > 0xFF) {
        return 0xFFu;
    }
    return static_cast<uint32_t>(generated);
}

uint32_t DivideExactHOverSz(uint16_t h,
                            uint16_t sz,
                            uint32_t& flags) {
    if (static_cast<uint32_t>(sz) * 2u <= h) {
        flags |= kFlagDivideOverflow;
        return 0x1FFFFu;
    }

    const uint32_t shift = CountLeadingZeros16(sz);
    const uint32_t numerator = static_cast<uint32_t>(h) << shift;
    const uint32_t normalized = static_cast<uint32_t>(sz) << shift;
    const uint32_t divisor = normalized | 0x8000u;
    const uint32_t tableIndex =
        ((divisor & 0x7FFFu) + 0x40u) >> 7u;
    const int32_t x = static_cast<int32_t>(
        0x101u + UnrReciprocalTableEntry(tableIndex));
    const int32_t d = static_cast<int32_t>(ArithmeticShiftRight(
        static_cast<int64_t>(divisor) * -x + 0x80, 8u));
    const uint32_t reciprocal = static_cast<uint32_t>(
        ArithmeticShiftRight(
            static_cast<int64_t>(x) * (0x20000 + d) + 0x80,
            8u));
    const uint32_t result = static_cast<uint32_t>(
        (static_cast<uint64_t>(numerator) * reciprocal + 0x8000u) >>
        16u);
    return result > 0x1FFFFu ? 0x1FFFFu : result;
}

std::array<int32_t, 9> DecodeRotation(const Matrix3x4& matrix) {
    return {{
        SignExtendLow16(matrix.words[0]),
        SignExtendHigh16(matrix.words[0]),
        SignExtendLow16(matrix.words[1]),
        SignExtendHigh16(matrix.words[1]),
        SignExtendLow16(matrix.words[2]),
        SignExtendHigh16(matrix.words[2]),
        SignExtendLow16(matrix.words[3]),
        SignExtendHigh16(matrix.words[3]),
        SignExtendLow16(matrix.words[4]),
    }};
}

int64_t TransformRtptComponent(const std::array<int32_t, 9>& rotation,
                               const Matrix3x4& matrix,
                               const VertexS16& vertex,
                               std::size_t component,
                               uint32_t& flags) {
    const std::size_t row = component * 3u;
    const int64_t translation =
        static_cast<int64_t>(static_cast<int32_t>(matrix.words[5u + component]));
    int64_t value = translation * 4096ll +
                    static_cast<int64_t>(rotation[row]) * vertex.x;
    // The RTPT MAC pipeline sign-extends after the first two accumulation
    // stages. The final third rotation term is overflow-checked but remains
    // unwrapped for the command's pre-shift Z/IR3/SZ behavior.
    value = CheckAndSignExtendMac44(value, component, flags);
    value += static_cast<int64_t>(rotation[row + 1u]) * vertex.y;
    value = CheckAndSignExtendMac44(value, component, flags);
    value += static_cast<int64_t>(rotation[row + 2u]) * vertex.z;
    CheckMac123Overflow(value, component, flags);
    return value;
}

uint32_t PackSxyWord(int32_t sx, int32_t sy) {
    return (static_cast<uint32_t>(static_cast<uint16_t>(sx)) |
            (static_cast<uint32_t>(static_cast<uint16_t>(sy)) << 16));
}

uint32_t DivideCandidateHOverSz(uint32_t h, uint32_t sz) {
    if (sz == 0) {
        return 0x1FFFFu;
    }
    const uint64_t numerator = static_cast<uint64_t>(h) << 12;
    uint64_t quotient = numerator / sz;
    if (quotient > 0x1FFFFu) {
        quotient = 0x1FFFFu;
    }
    return static_cast<uint32_t>(quotient);
}

int32_t ProjectCandidate(int64_t mac, uint32_t quotient, int32_t offset) {
    const int64_t center = static_cast<int64_t>(offset) >> 16;
    const int64_t projected =
        center + ((mac * static_cast<int64_t>(quotient)) >> 12);
    return static_cast<int32_t>(projected);
}

RtptRtps4VertexTrace8003F710 ComputeVertexTrace(
    const Matrix3x4& matrix,
    const VertexS16& vertex) {
    RtptRtps4VertexTrace8003F710 out{};

    const int32_t r11 = SignExtendLow16(matrix.words[0]);
    const int32_t r12 = SignExtendHigh16(matrix.words[0]);
    const int32_t r13 = SignExtendLow16(matrix.words[1]);
    const int32_t r21 = SignExtendHigh16(matrix.words[1]);
    const int32_t r22 = SignExtendLow16(matrix.words[2]);
    const int32_t r23 = SignExtendHigh16(matrix.words[2]);
    const int32_t r31 = SignExtendLow16(matrix.words[3]);
    const int32_t r32 = SignExtendHigh16(matrix.words[3]);
    const int32_t r33 = SignExtendLow16(matrix.words[4]);

    const int64_t x = vertex.x;
    const int64_t y = vertex.y;
    const int64_t z = vertex.z;
    const int64_t tx = static_cast<int32_t>(matrix.words[5]);
    const int64_t ty = static_cast<int32_t>(matrix.words[6]);
    const int64_t tz = static_cast<int32_t>(matrix.words[7]);

    out.transformCandidateKnown = true;
    out.macCandidate[0] = tx + ((static_cast<int64_t>(r11) * x +
                                static_cast<int64_t>(r12) * y +
                                static_cast<int64_t>(r13) * z) >> 12);
    out.macCandidate[1] = ty + ((static_cast<int64_t>(r21) * x +
                                static_cast<int64_t>(r22) * y +
                                static_cast<int64_t>(r23) * z) >> 12);
    out.macCandidate[2] = tz + ((static_cast<int64_t>(r31) * x +
                                static_cast<int64_t>(r32) * y +
                                static_cast<int64_t>(r33) * z) >> 12);
    out.irCandidate[0] = static_cast<int32_t>(out.macCandidate[0]);
    out.irCandidate[1] = static_cast<int32_t>(out.macCandidate[1]);
    out.irCandidate[2] = static_cast<int32_t>(out.macCandidate[2]);
    out.depthCandidateKnown = true;
    out.szCandidate = ClampUnsigned16(out.macCandidate[2]);
    return out;
}

}  // namespace

Rtpt3ExactOutput280030 ExecuteRtpt3Exact280030(
    const Rtpt3ExactInput280030& input) {
    Rtpt3ExactOutput280030 out{};
    const bool controlComplete =
        input.controlKnown &&
        input.control.geomScreenKnown &&
        input.control.geomOffsetKnown &&
        input.control.depthCueKnown &&
        input.control.geomScreen <= 0xFFFFu &&
        input.control.depthCueA >= -0x8000 &&
        input.control.depthCueA <= 0x7FFF;
    if (!input.matrixKnown || !input.verticesKnown || !controlComplete) {
        return out;
    }

    const std::array<int32_t, 9> rotation =
        DecodeRotation(input.matrix);
    const uint16_t h = static_cast<uint16_t>(input.control.geomScreen);
    const int16_t dqa = static_cast<int16_t>(input.control.depthCueA);
    uint32_t flags = 0u;

    for (std::size_t vertexIndex = 0u;
         vertexIndex < input.vertices.size();
         ++vertexIndex) {
        const VertexS16& vertex = input.vertices[vertexIndex];
        std::array<int64_t, 3> rawMac{};
        std::array<int32_t, 3> mac{};
        for (std::size_t component = 0u; component < rawMac.size();
             ++component) {
            rawMac[component] = TransformRtptComponent(
                rotation, input.matrix, vertex, component, flags);
            mac[component] = TruncateSigned32(
                ArithmeticShiftRight(rawMac[component], 12u));
        }

        const int32_t ir1 = ClampIr123(mac[0], 0u, flags);
        const int32_t ir2 = ClampIr123(mac[1], 1u, flags);
        // RTPT tests the pre-MAC32 44-bit Z result (after SAR 12) for the IR3
        // saturation flag; the separately clamped MAC3 register value is not
        // needed by this three-vertex output contract.
        const int32_t shiftedZ = TruncateSigned32(
            ArithmeticShiftRight(rawMac[2], 12u));
        ClampIr123(shiftedZ, 2u, flags);

        const uint16_t sz = ClampSz(shiftedZ, flags);
        const uint32_t quotient = DivideExactHOverSz(h, sz, flags);

        const int64_t sxMac0 =
            static_cast<int64_t>(quotient) * ir1 +
            input.control.geomOffsetX;
        const int64_t syMac0 =
            static_cast<int64_t>(quotient) * ir2 +
            input.control.geomOffsetY;
        CheckMac0Overflow(sxMac0, flags);
        CheckMac0Overflow(syMac0, flags);

        const int32_t sx = ClampScreenCoordinate(
            ArithmeticShiftRight(sxMac0, 16u),
            kFlagSxSaturated,
            flags);
        const int32_t sy = ClampScreenCoordinate(
            ArithmeticShiftRight(syMac0, 16u),
            kFlagSySaturated,
            flags);

        out.sxy[vertexIndex].known = true;
        out.sxy[vertexIndex].word = PackSxyWord(sx, sy);
        out.szAfterRtpt.elementKnown[vertexIndex + 1u] = true;
        out.szAfterRtpt.sz[vertexIndex + 1u] = sz;

        if (vertexIndex + 1u == input.vertices.size()) {
            const int64_t depthCueMac0 =
                static_cast<int64_t>(quotient) * dqa +
                input.control.depthCueB;
            CheckMac0Overflow(depthCueMac0, flags);
            out.ir0 = ClampIr0(static_cast<int32_t>(
                                   ArithmeticShiftRight(depthCueMac0, 12u)),
                               flags);
        }
    }

    if ((flags & kFlagErrorSourceMask) != 0u) {
        flags |= kFlagError;
    }
    out.known = true;
    out.flagAfterRtptKnown = true;
    out.flagAfterRtpt = flags;
    out.ir0Known = true;
    return out;
}

RtptRtps4Output8003F710 PsxCall8003F710_RotTransPers4RtptRtpsGap(
    const RtptRtps4Input8003F710& input) {
    RtptRtps4Output8003F710 out{};
    out.gap.matrixInputComplete = input.matrixKnown;
    out.gap.controlInputComplete =
        input.controlKnown &&
        input.control.geomScreenKnown &&
        input.control.geomOffsetKnown;
    out.gap.vertexInputComplete = input.verticesKnown;
    out.inputsCompleteForGeometry =
        input.matrixKnown &&
        input.verticesKnown &&
        out.gap.controlInputComplete;
    out.schedule.loadedRtptDataRegs0005 = input.verticesKnown;
    out.schedule.rtpt280030Called = input.verticesKnown;
    out.schedule.storedRtptSxy012 = input.verticesKnown;
    out.schedule.loadedRtpsDataRegs0001 = input.verticesKnown;
    out.schedule.rtps180001Called = input.verticesKnown;
    out.schedule.storedRtpsSxy2AndIr0 = input.verticesKnown;

    if (input.matrixKnown && input.verticesKnown) {
        for (std::size_t i = 0; i < out.vertexTrace.size(); ++i) {
            out.vertexTrace[i] =
                ComputeVertexTrace(input.matrix, input.vertices[i]);
        }
        out.gap.depthInputComputed = true;

        out.szAfterRtpt.elementCandidateKnown[1] = true;
        out.szAfterRtpt.elementCandidateKnown[2] = true;
        out.szAfterRtpt.elementCandidateKnown[3] = true;
        out.szAfterRtpt.candidateSz[1] = out.vertexTrace[0].szCandidate;
        out.szAfterRtpt.candidateSz[2] = out.vertexTrace[1].szCandidate;
        out.szAfterRtpt.candidateSz[3] = out.vertexTrace[2].szCandidate;

        out.szAfterRtps.elementCandidateKnown[0] = true;
        out.szAfterRtps.elementCandidateKnown[1] = true;
        out.szAfterRtps.elementCandidateKnown[2] = true;
        out.szAfterRtps.elementCandidateKnown[3] = true;
        out.szAfterRtps.candidateSz[0] = out.vertexTrace[0].szCandidate;
        out.szAfterRtps.candidateSz[1] = out.vertexTrace[1].szCandidate;
        out.szAfterRtps.candidateSz[2] = out.vertexTrace[2].szCandidate;
        out.szAfterRtps.candidateSz[3] = out.vertexTrace[3].szCandidate;
        out.szAfterRtps.candidateKnown = true;
        out.sz3AfterRtpsCandidateKnown = true;
        out.sz3AfterRtpsCandidate = out.vertexTrace[3].szCandidate;
    }

    if (input.controlKnown && input.control.geomScreenKnown) {
        for (std::size_t i = 0; i < out.division.size(); ++i) {
            GteDivisionTrace& division = out.division[i];
            division.inputsKnown = out.vertexTrace[i].depthCandidateKnown;
            division.h = input.control.geomScreen;
            if (division.inputsKnown) {
                division.sz = out.vertexTrace[i].szCandidate;
                division.quotient = DivideCandidateHOverSz(
                    division.h, division.sz);
                division.quotientCandidateKnown = true;
                division.divideOverflowCandidate =
                    division.sz == 0u || division.quotient == 0x1FFFFu;
                division.divideOverflowCandidateKnown = true;
            }
        }
        out.gap.divisionInputsComputed = out.gap.depthInputComputed;
    }

    if (input.controlKnown &&
        input.control.geomScreenKnown &&
        input.control.geomOffsetKnown) {
        for (std::size_t i = 0; i < out.projectionInput.size(); ++i) {
            GteProjectionInputTrace& projection = out.projectionInput[i];
            projection.inputsKnown =
                out.vertexTrace[i].transformCandidateKnown &&
                out.vertexTrace[i].depthCandidateKnown;
            projection.h = input.control.geomScreen;
            projection.ofx = input.control.geomOffsetX;
            projection.ofy = input.control.geomOffsetY;
            if (projection.inputsKnown) {
                projection.mac1 = out.vertexTrace[i].macCandidate[0];
                projection.mac2 = out.vertexTrace[i].macCandidate[1];
                projection.sz = out.vertexTrace[i].szCandidate;
                if (out.division[i].quotientCandidateKnown) {
                    projection.sxCandidate =
                        ProjectCandidate(projection.mac1,
                                         out.division[i].quotient,
                                         projection.ofx);
                    projection.syCandidate =
                        ProjectCandidate(projection.mac2,
                                         out.division[i].quotient,
                                         projection.ofy);
                    projection.sxyCandidateWord =
                        PackSxyWord(projection.sxCandidate,
                                    projection.syCandidate);
                    projection.sxyCandidateKnown = true;
                    out.sxy[i].candidateKnown = true;
                    out.sxy[i].candidateX = projection.sxCandidate;
                    out.sxy[i].candidateY = projection.syCandidate;
                    out.sxy[i].candidateWord = projection.sxyCandidateWord;
                }
            }
        }
    }

    if (out.vertexTrace[3].depthCandidateKnown) {
        out.sz3AfterRtpsCandidateKnown = true;
        out.sz3AfterRtpsCandidate = out.vertexTrace[3].szCandidate;
        out.returnValueCandidateKnown = true;
        out.returnValueCandidate = static_cast<uint32_t>(
            static_cast<int32_t>(out.sz3AfterRtpsCandidate) >> 2);
    }

    out.sxyWordsKnown = true;
    for (const GteSxy& sxy : out.sxy) {
        out.sxyWordsKnown = out.sxyWordsKnown && sxy.known;
    }

    // Keep non-matching inputs conservative until a PSX-authoritative GTE
    // trace covers that window.
    return out;
}

Mode25TriangleGeometryTrace TraceMode25TriangleGeometry(
    const Mode25TriangleGeometryInput& input) {
    Mode25TriangleGeometryTrace out{};
    out.sxy = input.sxy;
    out.szAfterRtpt = input.szAfterRtpt;

    out.projectedSxyKnown = true;
    std::array<uint32_t, 3> sxyWords{};
    for (std::size_t i = 0; i < input.sxy.size(); ++i) {
        const GteSxy& sxy = input.sxy[i];
        out.projectedSxyKnown = out.projectedSxyKnown && sxy.known;
        if (sxy.known) {
            sxyWords[i] = sxy.word;
        } else if (sxy.candidateKnown) {
            sxyWords[i] = sxy.candidateWord;
        } else {
            out.nclip.inputsCandidateKnown = false;
            sxyWords = {};
            break;
        }
        out.nclip.inputsCandidateKnown = true;
    }
    out.nclip.inputsAuthoritative = out.projectedSxyKnown;
    if (out.nclip.inputsCandidateKnown) {
        const int64_t x0 = static_cast<int16_t>(sxyWords[0] & 0xFFFFu);
        const int64_t y0 = static_cast<int16_t>(sxyWords[0] >> 16u);
        const int64_t x1 = static_cast<int16_t>(sxyWords[1] & 0xFFFFu);
        const int64_t y1 = static_cast<int16_t>(sxyWords[1] >> 16u);
        const int64_t x2 = static_cast<int16_t>(sxyWords[2] & 0xFFFFu);
        const int64_t y2 = static_cast<int16_t>(sxyWords[2] >> 16u);
        out.nclip.mac0Candidate =
            x0 * y1 + x1 * y2 + x2 * y0 -
            x0 * y2 - x1 * y0 - x2 * y1;
        out.nclip.candidateKnown = true;
        if (out.nclip.inputsAuthoritative) {
            out.nclip.known = true;
            out.nclip.mac0 = TruncateSigned32(out.nclip.mac0Candidate);
            out.nclip.overflowKnown = true;
            out.nclip.overflow =
                out.nclip.mac0Candidate < -0x80000000ll ||
                out.nclip.mac0Candidate > 0x7FFFFFFFll;
        }
    }

    out.avsz3.inputsAuthoritative = input.zScaleFactor3Known;
    out.avsz3.inputsCandidateKnown = input.zScaleFactor3Known;
    std::array<uint32_t, 3> depth{};
    for (std::size_t i = 0; i < depth.size(); ++i) {
        const std::size_t fifoIndex = i + 1u;
        if (input.szAfterRtpt.elementKnown[fifoIndex]) {
            depth[i] = input.szAfterRtpt.sz[fifoIndex];
        } else if (input.szAfterRtpt.elementCandidateKnown[fifoIndex]) {
            depth[i] = input.szAfterRtpt.candidateSz[fifoIndex];
            out.avsz3.inputsAuthoritative = false;
        } else {
            out.avsz3.inputsCandidateKnown = false;
            out.avsz3.inputsAuthoritative = false;
            break;
        }
    }
    if (out.avsz3.inputsCandidateKnown) {
        out.avsz3.zScaleFactor3 = input.zScaleFactor3;
        const int64_t sum = static_cast<int64_t>(depth[0]) + depth[1] +
                            depth[2];
        out.avsz3.mac0Candidate =
            sum * static_cast<int64_t>(input.zScaleFactor3);
        const int64_t rawOtz = out.avsz3.mac0Candidate >> 12;
        out.avsz3.saturationCandidate = rawOtz < 0 || rawOtz > 0xFFFF;
        out.avsz3.otzCandidate = static_cast<uint16_t>(
            ClampUnsigned16(rawOtz));
        out.avsz3.candidateKnown = true;
        const bool zsf3Representable =
            input.zScaleFactor3 >= -0x8000 &&
            input.zScaleFactor3 <= 0x7FFF;
        if (out.avsz3.inputsAuthoritative && zsf3Representable) {
            out.avsz3.known = true;
            out.avsz3.mac0 = TruncateSigned32(out.avsz3.mac0Candidate);
            out.avsz3.otz = out.avsz3.otzCandidate;
            out.avsz3.saturationKnown = true;
            out.avsz3.saturated = out.avsz3.saturationCandidate;
        }
    }

    if (out.nclip.known) {
        out.visibilityKnown = true;
        out.visible = out.nclip.mac0 > 0;
    }
    if (out.avsz3.known) {
        out.otzKnown = true;
        out.otz = out.avsz3.otz;
    }
    return out;
}

}  // namespace PrPsxGteDirect
